### ISSUE TITLE
When creating a sequelize model with a Datatype as `VIRTUAL` a migration is attempted

### ISSUE THREAD

**Issue by aaronesilva** [ariga/atlas-provider-sequelize#16]
Virtual data type fields shouldn't attempt to generate migrations

```
      test_id: {
        type: DataTypes.VIRTUAL,
        get() {
          return this.id;
        },
      },
```

Receiving error when generating migrations from sequelize models:
```
pq: type "virtual" does not exist
```

**Comment by ronenlu** [comment]
@aaronesilva Thank you for the reporting, we fixed the issue, you can install the latest atlas-provider by running:

```
npm i @ariga/atlas-provider-sequelize
```
